parameters:
    glifery_crud_abstract_data.event_listener.controller_event_handler.class: Glifery\CrudAbstractDataBundle\EventListener\ControllerEventHandler
    glifery_crud_abstract_data.service.crud_route_manager.class: Glifery\CrudAbstractDataBundle\Service\CrudRouteManager
    glifery_crud_abstract_data.service.crud_pool.class: Glifery\CrudAbstractDataBundle\Service\CrudPool
    glifery_crud_abstract_data.service.crud_form_factory.class: Glifery\CrudAbstractDataBundle\Service\CrudFormFactory
    glifery_crud_abstract_data.service.crud_datagrid_handler.class: Glifery\CrudAbstractDataBundle\Service\CrudDatagridHandler
    glifery_crud_abstract_data.service.crud_pagination.class: Glifery\CrudAbstractDataBundle\Service\CrudPagination

    glifery_crud_abstract_data.service.field_type_handler.simple.class: Glifery\CrudAbstractDataBundle\Service\FieldTypeHandler\SimpleFieldTypeHandler
    glifery_crud_abstract_data.service.field_type_handler.datetime.class: Glifery\CrudAbstractDataBundle\Service\FieldTypeHandler\DatetimeFieldTypeHandler
    glifery_crud_abstract_data.service.field_type_handler.entity.class: Glifery\CrudAbstractDataBundle\Service\FieldTypeHandler\EntityFieldTypeHandler

services:
    glifery_crud_abstract_data.service.crud_pool:
        class: %glifery_crud_abstract_data.service.crud_pool.class%
        arguments:
            RouteManager:    @glifery_crud_abstract_data.service.crud_route_manager
            FormFactory:     @glifery_crud_abstract_data.service.crud_form_factory
            DatagridHandler: @glifery_crud_abstract_data.service.crud_datagrid_handler
            Pagination:      @glifery_crud_abstract_data.service.crud_pagination

    glifery_crud_abstract_data.service.crud_route_manager:
        class: %glifery_crud_abstract_data.service.crud_route_manager.class%
        arguments: [@router]

    glifery_crud_abstract_data.service.crud_form_factory:
        class: %glifery_crud_abstract_data.service.crud_form_factory.class%
        arguments: [@form.factory]

    glifery_crud_abstract_data.service.crud_datagrid_handler:
        class: %glifery_crud_abstract_data.service.crud_datagrid_handler.class%
        calls:
            - ['registerFieldType', ['boolean', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:boolean.html.twig']]
            - ['registerFieldType', ['string', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:simple.html.twig']]
            - ['registerFieldType', ['integer', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:simple.html.twig']]
            - ['registerFieldType', ['float', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:simple.html.twig']]
            - ['registerFieldType', ['array', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:array.html.twig']]
            - ['registerFieldType', ['datetime', @glifery_crud_abstract_data.service.field_type_handler.datetime, 'GliferyCrudAbstractDataBundle:FieldType:datetime.html.twig']]
            - ['registerFieldType', ['entity', @glifery_crud_abstract_data.service.field_type_handler.entity, 'GliferyCrudAbstractDataBundle:FieldType:entity.html.twig']]
            - ['registerFieldType', ['_actions', @glifery_crud_abstract_data.service.field_type_handler.simple, 'GliferyCrudAbstractDataBundle:FieldType:actions.html.twig']]

    glifery_crud_abstract_data.service.crud_pagination:
        class: %glifery_crud_abstract_data.service.crud_pagination.class%

    glifery_crud_abstract_data.service.field_type_handler.simple:
        class: %glifery_crud_abstract_data.service.field_type_handler.simple.class%

    glifery_crud_abstract_data.service.field_type_handler.datetime:
        class: %glifery_crud_abstract_data.service.field_type_handler.datetime.class%

    glifery_crud_abstract_data.service.field_type_handler.entity:
        class: %glifery_crud_abstract_data.service.field_type_handler.entity.class%
        arguments: [@doctrine.orm.entity_manager]

    glifery_crud_abstract_data.event_listener.controller_event_handler:
        class: %glifery_crud_abstract_data.event_listener.controller_event_handler.class%
        arguments: [@router, @service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }